i.MX8MP: add ENET_QOS_IRQS define for enet_qos driver
Add missing ENET_QOS_IRQS define that is needed for enet_qos driver.
This fixes the following error:
/path/to/mcuxsdk/drivers/enet_qos/fsl_enet_qos.c:189:43: error:
'ENET_QOS_IRQS' undeclared here (not in a function); did you mean
'ENET_QOS_IRQn'?
  189 | static const IRQn_Type s_enetqosIrqId[] = ENET_QOS_IRQS;
      |                                           ^~~~~~~~~~~~~
      |                                           ENET_QOS_IRQn

Signed-off-by: Aziz Sellami <aziz.sellami@nxp.com>